### ISSUE TITLE
Confirmations are not always sent

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#12]
Sometimes it is necessary to confirm courses multiple times to be present in the "Check Confirmations" view. This also occurs when confirming only one couple, however is not reproducible consistently.
I consider this an urgent but since it may cause confirmation mails not to be sent.

**Comment by gitsimon** [comment]
This is a known issue with the server and most probably to memory problems on the current (underspecified server). Under "Tools"->"Check Confirmation" one can check which confirmations have not been sent and have to be reconfirmed (workaround until problem is solved).
