### ISSUE TITLE
Subscribes: see # confirmed in ()

### ISSUE THREAD

**Issue by andraema** [gitsimon/tq_website#14]
bei subscribes: in Klammern bitte die Anzahl schon bestätigter Schüler mit hinschreiben. Das erleichtert die Arbeit :D

**Comment by gitsimon** [comment]
to avoid messing with admin templates, we avoid adding this information into the admin view. with the [statistics overview](https://tanzquotient.org/en/courses/auth/) this should be solved in even more user friendly way
