### ISSUE TITLE
DoesNotExist: Course matching query does not exist.

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#22]
`Internal Server Error: /en/courses/detail/93/
Traceback (most recent call last):
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/cms/utils/decorators.py", line 17, in inner
   return func(request, *args, **kwargs)
 File "/webapps/tq_website/courses/views.py", line 121, in subscription
   'course': Course.objects.get(id=course_id),
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
   self.model._meta.object_name
DoesNotExist: Course matching query does not exist.

Request repr(): 
<WSGIRequest
path:/en/courses/detail/93/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'*****',
'HTTP_ACCEPT': '*/*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_CACHE_CONTROL': 'no-cache',
'HTTP_CONNECTION': 'close',
'HTTP_FROM': 'bingbot(at)microsoft.com',
'HTTP_HOST': 'tq.vseth.ethz.ch',
'HTTP_PRAGMA': 'no-cache',
'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
'HTTP_X_FORWARDED_FOR': '207.46.13.6',
'PATH_INFO': u'/en/courses/detail/93/',
'QUERY_STRING': '',
'RAW_URI': '/en/courses/detail/93/',
'REMOTE_ADDR': '',
'REQUEST_METHOD': 'GET',
'SCRIPT_NAME': u'',
'SERVER_NAME': 'tq.vseth.ethz.ch',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SOFTWARE': 'gunicorn/19.3.0',
'gunicorn.socket': <socket._socketobject object at 0x7fc90b055050>,
'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fc90b2b7e10>,
'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
'wsgi.input': <gunicorn.http.body.Body object at 0x7fc90b2c41d0>,
'wsgi.multiprocess': True,
'wsgi.multithread': False,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>`

**Comment by martinzellner** [comment]
Looks like this was only an issue because of the request being a bot. Would still be nice to see that fixed.

**Comment by gitsimon** [comment]
I think this was also fixed in 0fd1bb4480cb7d155083127ef0320ba3678893f4
