### ISSUE TITLE
KeyError: 'subscription_result'

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#28]
Internal Server Error: /de/courses/detail/133/subscription_done
Traceback (most recent call last):
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/cms/utils/decorators.py", line 17, in inner
   return func(request, *args, **kwargs)
 File "/webapps/tq_website/courses/views.py", line 180, in subscription_done
   'message': request.session['subscription_result'],
 File "/webapps/tq_website/env/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
   return self._session[key]
KeyError: 'subscription_result'

Request repr(): 
<WSGIRequest
path:/de/courses/detail/133/subscription_done,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'***',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'de-de',
'HTTP_CONNECTION': 'close',
'HTTP_HOST': 'tq.ethz.ch',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4',
'HTTP_X_FORWARDED_FOR': '83.79.196.221',
'PATH_INFO': u'/de/courses/detail/133/subscription_done',
'QUERY_STRING': '',
'RAW_URI': '/de/courses/detail/133/subscription_done',
'REMOTE_ADDR': '',
'REQUEST_METHOD': 'GET',
'SCRIPT_NAME': u'',
'SERVER_NAME': 'tq.ethz.ch',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.0',
'SERVER_SOFTWARE': 'gunicorn/19.3.0',
'gunicorn.socket': <socket._socketobject object at 0x7fc90aca51a0>,
'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fc90afd9590>,
'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
'wsgi.input': <gunicorn.http.body.Body object at 0x7fc90afd9750>,
'wsgi.multiprocess': True,
'wsgi.multithread': False,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>`

**Comment by martinzellner** [comment]
When http://tq.ethz.ch/de/courses/detail/133/subscription_done is called directly.

**Comment by gitsimon** [comment]
I added checks on all the intermediary subscription views and I throw a SuspiciousOperation Exception (results in a Bad Request message)
see d5b3c3d094da682708d3aa3526e948291d418953
