### ISSUE TITLE
https breaks javascript loading

### ISSUE THREAD

**Issue by gitsimon** [gitsimon/tq_website#33]
https leads to blocking of some javascript side loads. this breaks many of boostrap components (dropdowns, modals). and breaks google analytics. **Check error messages from javascript console:**
> Blocked loading mixed active content "http://fonts.googleapis.com/css?family=Open+Sans:300,400,700"[Learn More] de
Blocked loading mixed active content "http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"[Learn More] de
Blocked loading mixed active content "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"[Learn More]

**Comment by martinzellner** [comment]
Try changing the URLs to https instead?

**Comment by gitsimon** [comment]
yes, and even better use the protocol unspecific version for urls `//domain.com` (the double slash is needed to make it external url)
