### ISSUE TITLE
admin redirects to https instead http

### ISSUE THREAD

**Issue by gitsimon** [gitsimon/tq_website#35]
after each admin change, it redirects to http version -> gets blocked in most browsers due to mixed content

Things tried (no success):

- `SECURE_SSL_REDIRECT = True` in `settings_local.py`: leads to infinite loop of redirection

**Comment by martinzellner** [comment]
can you specify "admin change"?

**Comment by martinzellner** [comment]
I cannot reproduce this issue thats why I reassigned it to @gitsimon.

**Comment by gitsimon** [comment]
for me it happens in all browsers. it seems that django admin forms are using reverse url function that redirects to a http instead of https link.
Maybe [sslify](https://github.com/rdegges/django-sslify) is a solution:
It adds a middleware to enforce https on all urls

**Comment by martinzellner** [comment]
Are you using Firefox? Melissa is also experiencing this bug...

**Comment by gitsimon** [comment]
It has disappeared for me since upgrade to django 1.9, python 3+

**Comment by martinzellner** [comment]
Great 👍
