### ISSUE TITLE
Manually mark unmatched people as confirmed

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#36]
It should be possible to mark unmatched subscriptions as confirmed if people want to take the course alone.

**Comment by gitsimon** [comment]
No this is a fundamental decision that partner courses can not be attended alone. there is a corresponding flag for a course to make it a single-subscribing course.
What could be done is to allow a third course type with optional partner subscription. But for most of the partner courses this leads to uneven gender distribution.

**Comment by martinzellner** [comment]
How is the status for this one?

**Comment by martinzellner** [comment]
@gitsimon ?
