### ISSUE TITLE
Timetable for Trainings

### ISSUE THREAD

**Issue by gitsimon** [gitsimon/tq_website#38]
Would be nice to have a list/timetable for some courses where the program/teacher changes every week such as the Standard/Latein Training. See attachment for a sketch
![whatsapp-image](https://cloud.githubusercontent.com/assets/2462928/15632938/0cb0aa12-25a1-11e6-83d9-2460bde53c02.jpg)

**Comment by martinzellner** [comment]
This can be easily done manually.
