### ISSUE TITLE
.env only works with zsh

### ISSUE THREAD

**Issue by martinzellner** [gitsimon/tq_website#75]

**Comment by renatobellotti** [comment]
What does this mean?
According to [this page](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option), the environment variables are passed to the container. zsh is not even mentioned. Therefore I guess this issue would be a bug in docker...
What does not work for you?

**Comment by gitsimon** [comment]
First, old version of docker-compose did not support environment variables, but this should not be the problem. Some versions of bash may not pass the environment variables from .env file *automatically* to docker-compose calls. There is not much we can do about this, so I close this issue.

**Comment by martinzellner** [comment]
From my experience, some lines in the `.env` file lack proper escaping that works for bash and zsh. Bash sucks anyways, so this is no big deal. Nevertheless I think we should consider mentioning this point in the setup instructions.
