### ISSUE TITLE
Update Address in profile does not work

### ISSUE THREAD

**Issue by gitsimon** [gitsimon/tq_website#89]
In user profile address is reset to old value on save.

**Comment by roggnroll** [comment]
![bildschirmfoto 2017-09-19 um 11 30 34](https://user-images.githubusercontent.com/26879902/30585710-07ddb948-9d2e-11e7-9166-8e734760ca0e.png)
The new value goes to the save() function... I don't understand why it is not updating the database... will look into it.

**Comment by gitsimon** [comment]
Yes, but I found out that nested model userprofile.address is not saved automatically!

**Comment by roggnroll** [comment]
Ah, nice @gitsimon ! And if the user is created it doesn't go through this piece of code and that's why initially the address is saved, is that right?
